name: NBA
version: 0.1.0.0

ghc-options: -Wall -Werror

# global dependency:
dependencies:
  - aeson
  - async
  - base
  - base64-bytestring
  - bson
  - bytestring
  - http-client
  - http-conduit
  - http-types
  - lens
  - lens-aeson
  - mongoDB
  - stm
  - text
  - time
  - wreq

library:
  source-dirs: src/
  exposed-modules:
    - Lib
    - Models.BoxScores
    - Models.Games
    - Models.TeamGameLogs
    - Queries.GameQueries
    - Queries.BoxScoreQueries
    - Queries.GameLogQueries
    
    
  dependencies:
    - utf8-string
  
#create a section for our executables (only will have one called run-my-...
executables:
  fill-teams-into-db-2016-2017:
    source-dirs: app/
    main: FillTeamsDB.hs
    
    dependencies:
      NBA

  fill-games-into-db-2016-2017:
    source-dirs: app/
    main: FillGamesDB.hs
    
    dependencies:
      NBA

  fill-boxscores-into-db-2016-2017:
    source-dirs: app/
    main: FillBoxScoresDB.hs
    
    dependencies:
      NBA

tests:
  MyFirstProject-test:
    source-dirs: test/
    main: Spec.hs
    dependencies:
      NBA
